language: 
  - c
  - cxx

matrix:
    include:
        - os: osx
          addons:
            homebrew:
              packges:
                - libedit
          env:
            - PKG_CONFIG_PATH="/usr/local/opt/libedit/lib/pkgconfig"

        - os: linux
          env:
            - PKG_CONFIG_PATH="/usr/local/opt/libedit/lib/pkgconfig"

        - os: windows

install:
    # Get all the directories
    - git clone https://github.com/mbrazeau/morphy.release.test.git
    - cd mpl
    - git checkout development
    - cd ../nui
    - git checkout dev
    - cd ..
    - cd build

script:
    - cd ${TRAVIS_BUILD_DIR}/build
    - python build.py

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - make clean

skip_cleanup: true
