language: 
  - c
  - cxx

matrix:
    include:
        - os: osx
          addons:
            homebrew:
              packges:
                - libedit
          env:
            - PKG_CONFIG_PATH="/usr/local/opt/libedit/lib/pkgconfig"

        - os: linux
          addons:
            apt:
            sources:
              - ubuntu-toolchain-r-test
            packages:
              - g++-6
          dist: xenial
          before_install:
            - sudo apt-get install -y libedit-dev
          env:
            - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
            - PKG_CONFIG_PATH="/usr/local/opt/libedit/lib/pkgconfig"

        - os: windows

install:
    # Get all the directories
    - git clone https://github.com/mbrazeau/morphy.release.test.git
    - cd mpl
    - git checkout development
    - cd ../nui
    - git checkout dev
    - cd ..
    - cd build

script:
    - cd ${TRAVIS_BUILD_DIR}/build
    - python build.py

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - make clean

skip_cleanup: true
