language: 
  - c
  - cxx

matrix:
    include:
        - os: osx
          addons:
            homebrew:
              packges:
                - libedit
          env:
              - PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/opt/libedit/lib/pkgconfig
          script:
            - python build.py
            - cd ..
            - cat run.txt | ./install/bin/morphy_nui_v0b1

        - os: linux
          dist: xenial
          before_install:
            - sudo apt-get install -y libedit-dev
          env:
            - PKG_CONFIG_PATH="/usr/local/opt/libedit/lib/pkgconfig"
          script:
            - python build.py
            - cd ..
            - ls .
            - ls ..
            - pwd .
            - cat run.txt | ./install/bin/morphy_nui_v0b1

        - os: windows
          script:
            - python build.py
            - cd ..
            - cat run.txt | ./install/bin/morphy_nui_v0b1.exe

install:
    # Get all the directories
    - git pull --recurse-submodules 
    - cd mpl
    - git checkout development
    - cd ../nui
    - git checkout dev
    - cd ..
    - cd build

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - make clean

skip_cleanup: true
